
apiVersion: v1
kind: Namespace
metadata:
  name: curl-yelb
  labels:
    name: curl-yelb
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-yelb
  namespace: curl-yelb
  annotations:
    com.illumio.app: friendly-user
    com.illumio.role: good
  labels:
    app: curl-yelb
spec:
  restartPolicy: Never
  containers:
    - name: curl-yelb
      image: alpine:3.20
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh", "-c" ]
      args:
        - |
          set -eux
          apk add --no-cache curl
          # Curl to the endpoint every 10 minutes
          while true; do
            curl -sS http://yelb-ui.yelb.svc.cluster.local
            curl -sS http://yelb-ui.yelb.svc.cluster.local/api/chipotle
            curl -sS http://yelb-ui.yelb.svc.cluster.local/api/ihop
            curl -sS http://yelb-ui.yelb.svc.cluster.local/api/outback
            curl -sS http://yelb-ui.yelb.svc.cluster.local/api/bucadibeppo
            sleep 600
          done
          # Pod keep alive
          sleep infinity
